site_name: Emilien Breton&nbsp;&nbsp;|&nbsp;&nbsp;Notes
repo_url: https://github.com/Bricktech2000/Notes/
docs_dir: mkdocs
dev_addr: 0.0.0.0:8000

theme:
  name: material
  palette:
    scheme: slate
  font:
    code: Fira Code VF
  features:
    - navigation.instant
    - navigation.tracking
    - toc.follow
    - toc.integrate
  logo: icon.svg
  favicon: icon.svg
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - mdx_truly_sane_lists

extra_javascript:
  - script.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - styles.css
  - https://fonts.googleapis.com/css?family=Fira%20Code
